Repository Dev-roll/thundercard, pull requests merged in 2022-09, with the labels that each got.

#38 chore: get uid from firebaseauth
  lib/Thundercard.dart
  lib/login.dart
  lib/main.dart
Labels: firebase

#43 Keigomichi/upload-image
  lib/List.dart
  lib/main.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: firebase

#52 perf: login easily
  lib/login.dart
Labels: bug

#57 lonin with another account
  lib/login.dart
Labels: enhancement, flutter/dart

#67 Cardseditor/issue20
  lib/Account.dart
Labels: bug

#72 fix: fix uploading image
  lib/List.dart
Labels: bug, flutter/dart

#73 fix: show list variably
  lib/List.dart
Labels: bug, enhancement, flutter/dart

#74 fix: fix list
  lib/List.dart
Labels: bug, flutter/dart

#75 fix: fix list
  lib/Account.dart
  lib/List.dart
  lib/widgets/my_cards.dart
Labels: bug, flutter/dart

#88 chore: display account info based on uid
  lib/Account.dart
Labels: firebase

#89 feat: add cards to list
  android/app/src/main/AndroidManifest.xml
  lib/List.dart
  lib/upload_image_page.dart
Labels: enhancement, flutter/dart

#95 fix upload button
  lib/upload_image_page.dart
Labels: enhancement, flutter/dart

#100 fix: add is_user parameter
  lib/upload_image_page.dart
Labels: enhancement, flutter/dart

#106 refactor: refactoring
  lib/upload_image_page.dart
Labels: enhancement

#114 feat: exchange cards with qr code
  lib/add_card.dart
  lib/widgets/my_qr_code.dart
  lib/widgets/scan_qr_code.dart
Labels: enhancement, flutter/dart

#116 style: unify file name with snake case
  lib/widgets/scan_qr_code.dart
Labels: enhancement

#118 chore: add auth_gate using flutterfire_ui
  lib/account.dart
  lib/auth_gate copy.dart
  lib/auth_gate.dart
  lib/main.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: flutter/dart, firebase

#126 feat: display info
  lib/notifications.dart
Labels: enhancement, flutter/dart

#140 Cardseditor/issue117
  lib/notifications.dart
Labels: bug, enhancement, firebase

#151 feat: correct order, read, etc
  lib/account_registration.dart
  lib/notifications.dart
  lib/widgets/notification_item.dart
Labels: enhancement

#153 Cardseditor/issue141
  lib/account_registration.dart
Labels: bug

#161 fix: display bio
  lib/list.dart
  lib/widgets/my_card_data.dart
Labels: bug

#165 fix: fix data structure and read management
  lib/account_registration.dart
  lib/notifications.dart
  lib/widgets/notification_item.dart
Labels: bug, enhancement

#185 Cardseditor/issue155
  lib/list.dart
  lib/upload_image_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, UI/UX

#187 chore: fix UI adding a real card
  lib/upload_image_page.dart
Labels: enhancement, UI/UX

#194 feat: 情報の表示・非表示、通知の一斉操作、カード上のURLの反映
  lib/account.dart
  lib/card_details.dart
  lib/notifications.dart
  lib/upload_image_page.dart
  lib/widgets/card_info.dart
  lib/widgets/maintenance.dart
  lib/widgets/my_card_data.dart
  lib/widgets/return_url.dart
Labels: enhancement, flutter/dart, firebase

#211 feat: be able to delete card
  lib/account.dart
  lib/card_details.dart
  lib/widgets/maintenance.dart
Labels: enhancement, flutter/dart

#214 chore: データ構造を変更
  lib/account_editor.dart
  lib/add_card.dart
  lib/card_details.dart
  lib/constants.dart
  lib/list.dart
  lib/thundercard.dart
  lib/widgets/card_element.dart
  lib/widgets/card_info.dart
  lib/widgets/extended_card.dart
  lib/widgets/maintenance.dart
  lib/widgets/my_card.dart
  lib/widgets/my_card_data.dart
  lib/widgets/normal_card.dart
  lib/widgets/switch_card.dart
Labels: enhancement

#223 chore: 画像による名刺追加を改善
  lib/account.dart
  lib/card_details.dart
  lib/list.dart
  lib/upload_image_page.dart
  lib/widgets/card_info.dart
  lib/widgets/maintenance.dart
Labels: enhancement

#236 Cardseditor/issue195
  ios/Podfile.lock
  lib/account_editor.dart
  lib/account_registration.dart
  lib/api/return_url.dart
  lib/auth_gate.dart
  lib/constants.dart
  lib/widgets/extended_card.dart
  lib/widgets/normal_card.dart
  lib/widgets/switch_card.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, UI/UX, flutter/dart, firebase

#243 feat: enable to edit account info
  lib/account_editor.dart
Labels: enhancement, flutter/dart, firebase

#251 feat: show popup
  lib/account.dart
  lib/account_editor.dart
  lib/account_registration.dart
  lib/add_card.dart
  lib/card_details.dart
  lib/notifications.dart
  lib/upload_image_page.dart
  lib/widgets/maintenance.dart
  lib/widgets/notification_item.dart
  lib/widgets/notification_item_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#254 feat: new account page design
  ios/Podfile.lock
  lib/card_details.dart
  lib/chat.dart
  lib/main.dart
  lib/widgets/card_element.dart
  lib/widgets/card_info.dart
  lib/widgets/fullscreen_qr_code.dart
  lib/widgets/normal_card.dart
Labels: enhancement, UI/UX, flutter/dart
